# Generated by Django 4.1.5 on 2023-02-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Especialiad',
            new_name='especialiad',
        ),
    ]
