# Generated by Django 4.1.5 on 2023-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_especialiad_userdata_especialiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='centro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
