# Generated by Django 4.1.5 on 2023-02-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiamodel',
            name='habitos_toxicos',
        ),
        migrations.AddField(
            model_name='historiamodel',
            name='fumar',
            field=models.BooleanField(default=False),
        ),
    ]
