# Generated by Django 4.1.5 on 2023-02-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_remove_historiamodel_habitos_toxicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='complementarios_entregados',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='complementarios_indicados',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='diagnostico_presuntivo',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='plan_terapeutico',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='historiamodel',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='abdomen_auscultacion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='abdomen_inspecion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='abdomen_palpacion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='abdomen_percucion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='craneo_cara',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='cuello_auscultacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='cuello_inspecion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='cuello_palpitacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='cuello_percucion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='cuero_cabelludo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='fc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_cuello_uterino',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_flujo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_percucion_derecha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_percucion_izquierda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_percucion_lumbar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_tacto_vaginal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='genitourinario_vulva',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='habito_constitucional',
            field=models.CharField(choices=[('Brevilineo', 'Brevilineo'), ('Longilineo', 'Longilineo'), ('Normolineo', '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='imc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='lesiones',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='lugar_infiltrado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='mama_areolas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='mama_forma',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='mama_pezones',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='mama_simetria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='mama_tamanyo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='marcha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='murmullo_vesicular',
            field=models.CharField(choices=[('Rudo', 'Rudo'), ('Concervado', 'Concervado'), ('Disminuido', 'Disminuido'), ('Abolido', 'Abolido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_babinski',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_conducta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_dismetria',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_fondo_ojo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_glasgow_motor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_glasgow_ocular',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_glasgow_verbal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_lenguaje',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_motricidad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_paredes_craneales',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_reflejos_acomodacion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_reflejos_fotomotor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_reflejos_osteotendinosos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_rigidez',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_romberg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_sensibilidad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_taxia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='nervioso_temblor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='obstetrico_au',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='obstetrico_maniobre_leopold',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='osteomioarticular_articulaciones',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='osteomioarticular_columna_vertebral',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='osteomioarticular_ejes_oseos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='osteomioarticular_miembros',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='osteomioarticular_trofismo_muscular',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='peso_actual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='peso_habitual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='pulso',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='ruidos_cardiovascular',
            field=models.CharField(choices=[('Ritmico, Buen Tono', 'Ritmico, Buen Tono'), ('Ritmico, Bajo Tono', 'Ritmico, Bajo Tono'), ('Arritmico, Buen Tono', 'Arritmico, Buen Tono'), ('Arritmico, Bajo Tono', 'Arritmico, Bajo Tono')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='soplos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='tAuxiliar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='tReactal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='ta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='talla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='tejido_celular_subcutaneo',
            field=models.CharField(choices=[('Infiltrado', 'Infiltrado'), ('No Infiltrado', 'No Infiltrado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='tiraje',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='torax_forma',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultamodel',
            name='torax_piel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ComplementariosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=50)),
                ('complementario', models.CharField(max_length=500)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementarios', to='historias.consultamodel')),
            ],
        ),
    ]
