# Generated by Django 4.1.5 on 2023-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_consultamodel_complementarios_entregados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamodel',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
