# Generated by Django 4.1.5 on 2023-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_alter_historiamodel_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementariosmodel',
            name='complementario',
            field=models.ImageField(upload_to='historia/complementarios'),
        ),
    ]
