# Generated by Django 4.1.5 on 2023-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0006_alter_complementariosmodel_complementario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementariosmodel',
            name='complementario',
            field=models.ImageField(upload_to='complementarios'),
        ),
    ]
