# Generated by Django 4.1.5 on 2023-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0008_consultamodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementariosmodel',
            name='complementario',
            field=models.CharField(max_length=50),
        ),
    ]
