# Generated by Django 4.1.5 on 2023-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0009_alter_complementariosmodel_complementario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementariosmodel',
            name='complementario',
            field=models.FileField(upload_to='complementarios/'),
        ),
    ]
