# Generated by Django 4.1.5 on 2024-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0010_alter_complementariosmodel_complementario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultamodel',
            name='genitourinario_percucion_lumbar',
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='genitourinario_puntos_pielos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historiamodel',
            name='alergias',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historiamodel',
            name='antecedentes_familiares',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historiamodel',
            name='antecedentes_perosnales',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
