# Generated by Django 4.1.5 on 2024-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0011_remove_consultamodel_genitourinario_percucion_lumbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='estertores',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
