# Generated by Django 4.1.5 on 2024-01-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0013_procederesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procederesmodel',
            name='consulta',
        ),
    ]
