# Generated by Django 4.1.5 on 2024-01-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0014_remove_procederesmodel_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcederesRealizadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='historias.procederesmodel')),
                ('proceder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceder', to='historias.procederesmodel')),
            ],
        ),
    ]
