# Generated by Django 4.1.5 on 2024-01-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0016_procederesrealizadosmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procederesrealizadosmodel',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='historias.consultamodel'),
        ),
    ]
