# Generated by Django 4.1.5 on 2024-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0017_alter_procederesrealizadosmodel_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='genitourinario_glande',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='genitourinario_testiculo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
