# Generated by Django 4.1.5 on 2024-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0018_consultamodel_genitourinario_glande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='abdomen_region_inginal',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
